spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://192.168.9.130:8084
  zipkin:
    base-url: http://192.168.9.130:9411

server:
  port: 8761

eureka:
#  instance:
#    hostname: eureka
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.9.130:8761/eureka/,http://192.168.9.130:8762/eureka/,http://192.168.9.130:8763/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info